service: committrs-client

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1
  memorySize: 1024

plugins:
  - serverless-domain-manager
  - serverless-api-compression

custom:
  customDomain:
    domainName: committrs.io
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: 'committrs.io'
  contentEncoding:
    contentCompression: 1024


package:
  exclude:
    - node_modules/**

functions:
  app:
    handler: src/ssr/dist/index.ssr
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

